//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrambledPass.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrambledPass.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///a&amp;p
        ///a&apos;s
        ///aa
        ///aaa
        ///aaaa
        ///aaron
        ///ab
        ///aba
        ///ababa
        ///aback
        ///abase
        ///abash
        ///abate
        ///abbas
        ///abbe
        ///abbey
        ///abbot
        ///abbott
        ///abc
        ///abe
        ///abed
        ///abel
        ///abet
        ///abide
        ///abject
        ///ablaze
        ///able
        ///abner
        ///abo
        ///abode
        ///abort
        ///about
        ///above
        ///abrade
        ///abram
        ///absorb
        ///abuse
        ///abut
        ///abyss
        ///ac
        ///acadia
        ///accra
        ///accrue
        ///ace
        ///acetic
        ///ache
        ///acid
        ///acidic
        ///acm
        ///acme
        ///acorn
        ///acre
        ///acrid
        ///act
        ///acton
        ///actor
        ///acts
        ///acuity
        ///acute
        ///ad
        ///ada
        ///adage
        ///adagio
        ///adair
        ///adam
        ///adams
        ///adapt
        ///add
        ///added
        ///addict
        ///addis
        ///addle
        ///adele
        ///aden
        ///adept
        ///adieu
        ///adjust
        ///adler
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defaultWordList {
            get {
                return ResourceManager.GetString("defaultWordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap openFile {
            get {
                object obj = ResourceManager.GetObject("openFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reload {
            get {
                object obj = ResourceManager.GetObject("reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
